Rename functions, add check for wget/curl

diff --git a/.debian-scripts/functions b/.debian-scripts/functions
--- a/.debian-scripts/functions
+++ b/.debian-scripts/functions
@@ -1,15 +1,17 @@
-_dots () {
+print_dots() {
   printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
 }
 
-_get_stdout () {
+check_wgets() {
+    [[ "$(command -v curl)" || "$(command -v wget)" ]] || { echo "Error: curl or wget not installed, please install at least one of them. Exiting..." 1>&2 ; exit 1; }
+}
+
+url_stdout() {
+    check_wgets
     URL=$1
     if [ -x "$(which wget)" ] ; then
         curl -o- -sfL $URL
     elif [ -x "$(which curl)" ]; then
         wget -q $URL -O-
-    else
-        echo "Could not find curl or wget, please install one." >&2
-        exit 1
     fi
 }
